### PR TITLE
add 22h2

### PR DESCRIPTION
**Pull request by Andrysky**

### CODE REVIEW

**Review by 9840751500 — APPROVED** [review]

**Comment by PandaBianco2022** [comment]
is it possible to add windows 10 22h2 as well?

**Review by fleetimee — APPROVED** [review]

**Comment by Andrysky** [comment]
@PandaBianco2022 I think it's possible, but I don't have time right now.

**Comment by cheetahchen** [comment]
It seems not working on home edition

**Review by x9nico — APPROVED** [review]

**Comment by Hedwig7s** [comment]
> @PandaBianco2022 I think it's possible, but I don't have time right now.

Aw man

**Comment by XChikuX** [comment]
Works great on getting an ISO file from Windows 11 Home 21H2!!

@cheetahchen Did you try to Auto Upgrade?

**Review by XChikuX — APPROVED** [review]
Works great. Thanks for adding

**Comment by davidenco** [comment]
> is it possible to add windows 10 22h2 as well?

Check PR #230 - I've merged this PR and included Windows 10 22H2 support.

**Comment by cheetahchen** [comment]
worked after manualy run the script [Skip_TPM_Check_on_Dynamic_Update.cmd](https://github.com/Andrysky/MediaCreationTool.bat/blob/22h2/bypass11/Skip_TPM_Check_on_Dynamic_Update.cmd) first.

**Comment by XChikuX** [comment]
We can merge this no?

**Comment by aninus** [comment]
Why can't I download this installer?

**Pull request closed without merging**
