### PR TITLE
23H2 December Refresh

### PR DESCRIPTION
**Pull request by lzw29107**

### CODE REVIEW

**Comment by AveYo** [comment]
Thanks!

**Comment by tute123456** [comment]
thx!!!!!!!!!

**Comment by 3p1st3m1c** [comment]
24H2?

**Comment by DJSTEVE66** [comment]
Thanks.....
and when we will be able to have the Windows 11 24H2 version?
thanks again

**Comment by lzw29107** [comment]
> Thanks..... and when we will be able to have the Windows 11 24H2 version? thanks again

#311

**Pull request merged**
