### PR TITLE
Add Windows 10/11 22H2

### PR DESCRIPTION
**Pull request by davidenco**

### CODE REVIEW

**Review by rin-gil — APPROVED** [review]

**Review by hieuck — APPROVED** [review]

**Review by Ragefire117 — APPROVED** [review]

**Comment by bairog** [comment]
@AveYo merge this please. Thank you.

**Review by javifly — APPROVED** [review]

**Comment by turric4n** [comment]
What about this merge?

**Comment by AveYo** [comment]
Sorry, my screen time has been severely limited (even on phones) and this project requires many tests on a pc. I'm sort of back and rather overwhelmed with all the shit I've spawned online across multiple aliases. Good thing my stuff is usually low maintenance by design :)  
Won't merge this as my last snapshot has deviated more. I have some testing to do. 
I honestly hoped microsoft would re-release all versions in the mean time to address BlackLotus fuckery but they just don't care.

**Comment by ZeroGit2015** [comment]
I have Windows 11 21H2. Your changes are not work correctly. After  "22H2->AutoUpgrade->Create Iso" ran black window where was written "Access denied".  And than the window closed

**Comment by javifly** [comment]
is there already a modified version for the 23h2?

**Comment by javifly** [comment]
hank you very much! I have already seen the fork and the modification that you mention and I am downloading it right now. Thank you very much again.

https://github.com/lzw29107/MediaCreationTool.bat/tree/main


I have already tested it on a computer and it works perfectly.

**Pull request closed without merging**
