### PR TITLE
Update the script to add the option to download 10 22H2, 11 22H2, and 11 23H2

### PR DESCRIPTION
**Pull request by lzw29107**

### CODE REVIEW

**Comment by javifly** [comment]
ok

**Comment by javifly** [comment]
I just updated and everything went perfect. No error, reboot, etc... now I will test the equipment for a few days but the update is perfect. Thanks for the update

**Comment by HELPY4** [comment]
Thanks!!!1 It worked and helped me :)

**Review by AveYo — CHANGES_REQUESTED** [review]
Thank you!

**Review by AveYo — APPROVED** [review]
Thanks!

**Comment by afbrenckl** [comment]
what we actually want is so we can be able to copy the code and then put it into notepad like you did for the PSA: How to install Windows 22h2 for 23h2 because that is so much easier than a script so when are you going to do that.

**Pull request merged**
